#pragma once

#include "CoreMinimal.h"

namespace MCPErrorCodes
{
	static constexpr TCHAR TOOL_NOT_FOUND[] = TEXT("MCP.TOOL.NOT_FOUND");
	static constexpr TCHAR SCHEMA_INVALID_PARAMS[] = TEXT("MCP.SCHEMA.INVALID_PARAMS");
	static constexpr TCHAR IDEMPOTENCY_CONFLICT[] = TEXT("MCP.IDEMPOTENCY.CONFLICT");
	static constexpr TCHAR POLICY_DENY[] = TEXT("MCP.POLICY.DENY");
	static constexpr TCHAR LOCK_CONFLICT[] = TEXT("MCP.LOCK.CONFLICT");
	static constexpr TCHAR EDITOR_UNSAFE_STATE[] = TEXT("MCP.EDITOR.UNSAFE_STATE");
	static constexpr TCHAR JOB_NOT_FOUND[] = TEXT("MCP.JOB.NOT_FOUND");
	static constexpr TCHAR JOB_TIMEOUT[] = TEXT("MCP.JOB.TIMEOUT");
	static constexpr TCHAR JOB_CANCELED[] = TEXT("MCP.JOB.CANCELED");
	static constexpr TCHAR CHANGESET_NOT_FOUND[] = TEXT("MCP.CHANGESET.NOT_FOUND");
	static constexpr TCHAR CHANGESET_ROLLBACK_FAILED[] = TEXT("MCP.CHANGESET.ROLLBACK_FAILED");
	static constexpr TCHAR OBJECT_NOT_FOUND[] = TEXT("MCP.OBJECT.NOT_FOUND");
	static constexpr TCHAR ASSET_NOT_FOUND[] = TEXT("MCP.ASSET.NOT_FOUND");
	static constexpr TCHAR ASSET_ALREADY_EXISTS[] = TEXT("MCP.ASSET.ALREADY_EXISTS");
	static constexpr TCHAR ASSET_PATH_INVALID[] = TEXT("MCP.ASSET.PATH_INVALID");
	static constexpr TCHAR ASSET_CREATE_FAILED[] = TEXT("MCP.ASSET.CREATE_FAILED");
	static constexpr TCHAR ASSET_IMPORT_FAILED[] = TEXT("MCP.ASSET.IMPORT_FAILED");
	static constexpr TCHAR ASSET_IMPORT_UNSUPPORTED[] = TEXT("MCP.ASSET.IMPORT_UNSUPPORTED");
	static constexpr TCHAR ASSET_DUPLICATE_FAILED[] = TEXT("MCP.ASSET.DUPLICATE_FAILED");
	static constexpr TCHAR ASSET_RENAME_FAILED[] = TEXT("MCP.ASSET.RENAME_FAILED");
	static constexpr TCHAR ASSET_DELETE_FAILED[] = TEXT("MCP.ASSET.DELETE_FAILED");
	static constexpr TCHAR ASSET_REFERENCED[] = TEXT("MCP.ASSET.REFERENCED");
	static constexpr TCHAR CONFIRM_TOKEN_INVALID[] = TEXT("MCP.CONFIRM.TOKEN_INVALID");
	static constexpr TCHAR SETTINGS_CLASS_NOT_FOUND[] = TEXT("MCP.SETTINGS.CLASS_NOT_FOUND");
	static constexpr TCHAR SETTINGS_CONFIG_SAVE_FAILED[] = TEXT("MCP.SETTINGS.CONFIG_SAVE_FAILED");
	static constexpr TCHAR SETTINGS_VERIFY_FAILED[] = TEXT("MCP.SETTINGS.VERIFY_FAILED");
	static constexpr TCHAR SETTINGS_CONFIRM_TOKEN_INVALID[] = TEXT("MCP.SETTINGS.CONFIRM_TOKEN_INVALID");
	static constexpr TCHAR GAMEMODE_CLASS_INVALID[] = TEXT("MCP.GAMEMODE.CLASS_INVALID");
	static constexpr TCHAR GAMEMODE_OVERRIDE_NOT_FOUND[] = TEXT("MCP.GAMEMODE.OVERRIDE_NOT_FOUND");
	static constexpr TCHAR PROPERTY_NOT_EDITABLE[] = TEXT("MCP.PROPERTY.NOT_EDITABLE");
	static constexpr TCHAR SERIALIZE_UNSUPPORTED_TYPE[] = TEXT("MCP.SERIALIZE.UNSUPPORTED_TYPE");
	static constexpr TCHAR MATERIAL_PARAM_NOT_FOUND[] = TEXT("MCP.MATERIAL.PARAM_NOT_FOUND");
	static constexpr TCHAR NIAGARA_MODULE_KEY_NOT_FOUND[] = TEXT("MCP.NIAGARA.MODULE_KEY_NOT_FOUND");
	static constexpr TCHAR UMG_WIDGET_NOT_FOUND[] = TEXT("MCP.UMG.WIDGET_NOT_FOUND");
	static constexpr TCHAR SAVE_FAILED[] = TEXT("MCP.SAVE.FAILED");
	static constexpr TCHAR INTERNAL_EXCEPTION[] = TEXT("MCP.INTERNAL.EXCEPTION");
}
